# Generated by Django 4.2.29 on 2026-07-21 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('sku', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('rings', 'Rings'), ('necklaces', 'Necklaces'), ('bracelets', 'Bracelets'), ('earrings', 'Earrings')], default='rings', max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_stock', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('metal_type', models.CharField(blank=True, choices=[('yellow-gold', 'Yellow Gold'), ('white-gold', 'White Gold'), ('rose-gold', 'Rose Gold'), ('platinum', 'Platinum'), ('silver', 'Silver'), ('two-tone', 'Two-Tone')], max_length=30, null=True)),
                ('metal_karat', models.CharField(blank=True, choices=[('9K', '9ct'), ('14K', '14ct'), ('18K', '18ct'), ('22K', '22ct'), ('24K', '24ct'), ('950Pt', '950 Platinum'), ('925Ag', '925 Silver')], max_length=20, null=True)),
                ('diamond_cut', models.CharField(blank=True, choices=[('round', 'Round Brilliant'), ('princess', 'Princess'), ('oval', 'Oval'), ('pear', 'Pear'), ('cushion', 'Cushion'), ('emerald-cut', 'Emerald'), ('radiant', 'Radiant Cut'), ('marquise', 'Marquise'), ('asscher', 'Asscher'), ('heart', 'Heart')], max_length=30, null=True)),
                ('ring_style', models.CharField(blank=True, choices=[('solitaire', 'Solitaire'), ('halo', 'Halo'), ('pave', 'Pavé'), ('eternity', 'Eternity'), ('three-stone', 'Trilogy Three Stone'), ('vintage', 'Vintage'), ('cluster', 'Cluster')], max_length=30, null=True)),
                ('earring_type', models.CharField(blank=True, choices=[('studs', 'Studs'), ('hoops', 'Hoops'), ('drops', 'Drops'), ('huggies', 'Huggies'), ('climbers', 'Climbers'), ('chandelier', 'Chandelier')], max_length=30, null=True)),
                ('necklace_style', models.CharField(blank=True, choices=[('pendant', 'Pendant'), ('chain', 'Chain'), ('choker', 'Choker'), ('collar', 'Collar'), ('station', 'Station'), ('lariat', 'Lariat'), ('tennis', 'Tennis')], max_length=30, null=True)),
                ('bracelet_type', models.CharField(blank=True, choices=[('bangle', 'Bangle'), ('tennis', 'Tennis'), ('chain', 'Chain'), ('cuff', 'Cuff'), ('charm', 'Charm'), ('link', 'Link')], max_length=30, null=True)),
                ('gender', models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('unisex', 'Unisex')], default='women', max_length=20)),
                ('occasion', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
                'ordering': ['name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.product')),
            ],
            options={
                'ordering': ['size'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('public_id', models.CharField(blank=True, default='', max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.subcategory'),
        ),
    ]
