# Generated by Django 5.0.14 on 2026-07-26 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiamondType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='ring_style',
        ),
        migrations.AddField(
            model_name='product',
            name='band_fit',
            field=models.CharField(blank=True, choices=[('comfort', 'Comfort Fit'), ('standard', 'Standard/Traditional Fit')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='customisation_available',
            field=models.CharField(choices=[('yes', 'Yes'), ('on_request', 'On Request'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='engraving_available',
            field=models.CharField(choices=[('yes', 'Yes'), ('on_request', 'On Request'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='finish',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.collection'),
        ),
        migrations.CreateModel(
            name='DiamondSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carat_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('side_carat_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cut_grade', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('fair', 'Fair')], max_length=20, null=True)),
                ('colour_grade', models.CharField(blank=True, choices=[('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=2, null=True)),
                ('clarity_grade', models.CharField(blank=True, choices=[('FL', 'Flawless'), ('IF', 'Internally Flawless'), ('VVS1', 'VVS1'), ('VVS2', 'VVS2'), ('VS1', 'VS1'), ('VS2', 'VS2'), ('SI1', 'SI1'), ('SI2', 'SI2'), ('I1', 'I1'), ('I2', 'I2'), ('I3', 'I3')], max_length=10, null=True)),
                ('certification_lab', models.CharField(choices=[('GIA', 'GIA'), ('IGI', 'IGI'), ('none', 'Uncertified')], default='none', max_length=10)),
                ('certificate_number', models.CharField(blank=True, default='', max_length=100)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diamond_spec', to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='diamond_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.diamondtype'),
        ),
        migrations.AddField(
            model_name='product',
            name='styles',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.style'),
        ),
    ]
