# Generated by Django 5.0.14 on 2026-08-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_collection_diamondtype_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
