# Generated by Django 5.0.14 on 2026-08-28 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_video_url_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_keywords',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('metal_type', models.CharField(blank=True, choices=[('yellow-gold', 'Yellow Gold'), ('white-gold', 'White Gold'), ('rose-gold', 'Rose Gold'), ('platinum', 'Platinum'), ('silver', 'Silver'), ('two-tone', 'Two-Tone')], default='', max_length=30)),
                ('metal_karat', models.CharField(blank=True, choices=[('9K', '9ct'), ('14K', '14ct'), ('18K', '18ct'), ('22K', '22ct'), ('24K', '24ct'), ('950Pt', '950 Platinum'), ('925Ag', '925 Silver')], default='', max_length=20)),
                ('size', models.CharField(blank=True, default='', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'ordering': ['-is_default', 'id'],
            },
        ),
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'metal_type', 'metal_karat', 'size'), name='unique_product_variant_combination'),
        ),
    ]
