# Generated by Django 5.0.14 on 2026-08-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_diamondspecification_center_carat_weight_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_product_variant_combination',
        ),
        migrations.AddField(
            model_name='diamondspecification',
            name='certificate_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='diamondspecification',
            name='diamond_shape',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='diamondspecification',
            name='fluorescence',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='diamondspecification',
            name='number_of_diamonds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diamondspecification',
            name='polish',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='diamondspecification',
            name='symmetry',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='adjustable',
            field=models.CharField(choices=[('yes', 'Yes'), ('on_request', 'On Request'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='band_style',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='band_width',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='bangle_size',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='bangle_thickness',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='bangle_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='bangle_width',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='bracelet_length',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='bracelet_style',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='bracelet_thickness',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='bracelet_width',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='canonical_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='chain_included',
            field=models.CharField(choices=[('yes', 'Yes'), ('on_request', 'On Request'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='chain_length',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='chain_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='clasp_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='closure_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_type',
            field=models.CharField(blank=True, default='Standard Secure Shipping', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='depth',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='drop_length',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='earring_height',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='earring_style',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='earring_width',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='engraving_character_limit',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='product',
            name='engraving_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='estimated_delivery_time',
            field=models.CharField(blank=True, default='3-5 Business Days', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='gemstone_carat_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gemstone_colour',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='gemstone_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gemstone_included',
            field=models.CharField(choices=[('yes', 'Yes'), ('on_request', 'On Request'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='gemstone_origin',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='gemstone_shape',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='gemstone_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='inner_diameter',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='internal_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='made_to_order',
            field=models.CharField(choices=[('yes', 'Yes'), ('on_request', 'On Request'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='necklace_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='next_day_delivery_available',
            field=models.CharField(choices=[('yes', 'Yes'), ('on_request', 'On Request'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='og_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='og_image',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='og_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='opening_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='pendant_depth',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='pendant_height',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='pendant_included',
            field=models.CharField(choices=[('yes', 'Yes'), ('on_request', 'On Request'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='pendant_shape',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='pendant_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='pendant_width',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='personalisation_available',
            field=models.CharField(choices=[('yes', 'Yes'), ('on_request', 'On Request'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='production_time',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='resizable',
            field=models.CharField(choices=[('yes', 'Yes'), ('on_request', 'On Request'), ('no', 'No')], default='yes', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='ring_finish',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='ring_profile',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='ring_shape',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='ring_style',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='ring_thickness',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='ring_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thickness',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='allow_backorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='availability',
            field=models.CharField(default='in_stock', max_length=30),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='bangle_size',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='length',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='track_inventory',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('rings', 'Rings'), ('engagement-rings', 'Engagement Rings'), ('wedding-bands', 'Wedding Bands'), ('eternity-bands', 'Eternity Bands'), ('necklaces', 'Necklaces'), ('pendants', 'Pendants'), ('bracelets', 'Bracelets'), ('bangles', 'Bangles'), ('earrings', 'Earrings'), ('other', 'Other Jewellery')], default='rings', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'metal_type', 'metal_karat', 'size', 'length', 'bangle_size'), name='unique_product_variant_combination'),
        ),
    ]
