# Generated by Django 5.0.14 on 2026-07-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_stock_decremented_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reservation_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
