# Generated by Django 5.0.14 on 2026-07-23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(max_length=100)),
                ("razorpay_payment_id", models.CharField(max_length=100)),
                ("razorpay_order_id", models.CharField(blank=True, default="", max_length=100)),
                ("payload", models.JSONField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-received_at"]},
        ),
        migrations.AddConstraint(
            model_name="webhookevent",
            constraint=models.UniqueConstraint(
                fields=("event_type", "razorpay_payment_id"),
                name="unique_webhook_event_per_payment",
            ),
        ),
    ]
